erver:
  port: 8080
#  servlet:
#    context-path: /comjava

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/com_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Khoa@1105
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
